<<<<<<< HEAD
# These are supported funding model platforms

github: [LekoArts]
patreon: lekoarts
open_collective: # Replace with a single Open Collective username
ko_fi: lekoarts
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
=======
# These are supported funding model platforms

github: [LekoArts]
patreon: lekoarts
open_collective: # Replace with a single Open Collective username
ko_fi: lekoarts
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
>>>>>>> 8db8b6861bf852d9e97a9d896bba9404031b5302
custom: # Replace with a single custom sponsorship URL